version: '3.9'

networks:
  openapi-tutorial-net:
    name: openapi-tutorial-net
    driver: bridge

services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.4.6@sha256:ac30efa12f5a78ea981784d538243afc743ec59bb7823cbbeabe336beb68354b
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=none
    volumes:
      - "$HOME/neo4j-tutorial/data:/data"
      - "$HOME/neo4j-tutorial/logs:/logs"
    networks:
      - openapi-tutorial-net
    ports:
      - "7474:7474"
      - "7687:7687"
  tutorial-api:
    container_name: openapi-tutorial-server
    restart: unless-stopped
    build:
      context: ./systems-api
      dockerfile: Dockerfile
      labels: 
        - openapi-tutorial-api
    networks:
      - openapi-tutorial-net
    ports:
      - '3700:3700'