version: '3.9'

networks:
  openapi-tutorial-net:
    name: openapi-tutorial-net
    driver: bridge

services:

  openapi-tutorial-api:
    container_name: openapi-tutorial-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels: 
        - openapi-tutorial-api
    networks:
      - openapi-tutorial-net
    ports:
      - '127.0.0.1:3700:3700'
